use_frameworks!

platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'EOSWallet_Example' do
  pod 'EOSWallet', :path => '../'

  target 'EOSWallet_Tests' do
    inherit! :search_paths
    
  end
end
